# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4f2532a7d67996f2e086ce9eef8a0c9da48b1a982cf1b5c0bd5448228b142816da3b7410049f30b7311f3cd158dd60b1757c494ae1a2f32960d9ad96bb793e8f

test:
  secret_key_base: c8e1ba08b86da29b932ee899ebc114e75eb4c3ecc4b8ba11c6bf7f545636e6abe002813761c964a3400c51ea8aa67be0c2f20deb5909063d2daa8f7029ff967f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
